// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'full-width': string;
  'input-group': string;
  'svg-button': string;
  'template-selection-panel': string;
  'test-form-details': string;
}
export const cssExports: CssExports;
export default cssExports;
