branches: develop
repositoryUrl: 'https://github.com/ScenarioHunting/ScenarioHunting'
debug: 'true'
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/git'
    - assets:
        - package.json
        - package-lock.json
        - CHANGELOG.md
        - dist/**/*.{js,css}
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}