// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'image-button': string;
  'image-button-image': string;
  'image-button-text': string;
}
export const cssExports: CssExports;
export default cssExports;
