// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'imageButton': string;
  'imageInButton': string;
  'raw': string;
  'templateName': string;
  'test-item': string;
  'test-item-header': string;
  'test-steps-view-model-item': string;
}
export const cssExports: CssExports;
export default cssExports;
