// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'icon-run-tests': string;
  'test-failed': string;
  'test-item': string;
  'test-item-header': string;
  'test-not-run': string;
  'test-passed': string;
  'test-running': string;
  'test-running-error': string;
  'test-running-status': string;
  'test-skipped': string;
  'test-step-view-model-item': string;
  'test-steps-view-model-item': string;
  'tooltip': string;
  'tooltiptext': string;
}
export const cssExports: CssExports;
export default cssExports;
