// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'key-value-row': string;
  'property-key': string;
  'property-value': string;
  'step': string;
  'step-data-properties': string;
  'step-title': string;
  'waiting-for-step': string;
}
export const cssExports: CssExports;
export default cssExports;
