// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'property-input': string;
  'property-label': string;
  'step-data': string;
  'step-data-property': string;
  'step-title': string;
  'waiting-for-step': string;
}
export const cssExports: CssExports;
export default cssExports;
