# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js (16.10.0)
      uses: actions/setup-node@v2
      with:
        node-version: '16.10.0'

    - name: Install Pacakges 
      run: npm ci
      
    - name: Release Step 
      env: 
        CI: "" 
      run: npm run release

    - name: Run Semantic Release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        
    